export const metadata = {
  title: 'About GogyAI — Free AI Tools for Teachers',
  description: 'Learn about GogyAI — our mission to give every teacher worldwide free, powerful AI tools to save time and improve student outcomes.',
  alternates: { canonical: 'https://gogyai.com/about' },
}

const schema = {
  '@context': 'https://schema.org',
  '@type': 'WebPage',
  name: 'About GogyAI',
  url: 'https://gogyai.com/about',
  description: 'About GogyAI — free AI tools for teachers worldwide.',
}

export default function AboutPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
        <h1 className="text-3xl font-bold text-brand-800 mb-6">About GogyAI</h1>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-slate-800 mb-3">Our Mission</h2>
          <p className="text-slate-600 leading-relaxed">
            GogyAI was built with one goal: give every teacher on the planet free, powerful AI tools that save time, reduce admin burden, and help them focus on what matters most — their students. Teaching is one of the world's most important professions, and we believe AI should be an accessible assistant for every educator, regardless of location or budget.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-slate-800 mb-3">How Our Tools Work</h2>
          <p className="text-slate-600 leading-relaxed mb-3">
            Each GogyAI tool uses state-of-the-art AI models (Google Gemini and Groq Llama) to generate high-quality educational content in seconds. You fill in a short form with your specific requirements — subject, grade level, topic, and preferences — and the AI does the rest.
          </p>
          <p className="text-slate-600 leading-relaxed">
            All tools are completely free to use. No account, no subscription, no credit card. Just open a tool and start generating.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-slate-800 mb-3">Privacy Commitment</h2>
          <p className="text-slate-600 leading-relaxed">
            We take privacy seriously — especially because teachers work with student data. GogyAI collects no personally identifiable information from users. We do not collect any student data whatsoever. If you choose to use your own API key (for extended use), it is stored only in your browser's local storage and never transmitted to our servers.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-slate-800 mb-3">A Note on AI Output</h2>
          <p className="text-slate-600 leading-relaxed">
            AI-generated content is a starting point, not a finished product. Every piece of content generated by GogyAI should be reviewed by the teacher before use in the classroom. You are the expert — the AI is your assistant.
          </p>
        </section>
      </div>
    </>
  )
}
