export const metadata = {
  title: 'Disclaimer — GogyAI',
  description: 'GogyAI disclaimer — all AI-generated content must be reviewed before classroom use. Teacher judgment is always paramount.',
  alternates: { canonical: 'https://gogyai.com/disclaimer' },
}

const schema = {
  '@context': 'https://schema.org',
  '@type': 'WebPage',
  name: 'Disclaimer — GogyAI',
  url: 'https://gogyai.com/disclaimer',
}

export default function DisclaimerPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
        <h1 className="text-3xl font-bold text-brand-800 mb-2">Disclaimer</h1>
        <p className="text-slate-600 text-sm mb-8">Last updated: May 2025</p>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-slate-800 mb-3">Review Before Use</h2>
          <p className="text-slate-600 leading-relaxed">
            All content generated by GogyAI's AI tools <strong>must be reviewed and approved by the teacher</strong> before any classroom use. AI language models can produce inaccurate, incomplete, or contextually inappropriate content. You, as the educator, are the final authority.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-slate-800 mb-3">No Accuracy Guarantee</h2>
          <p className="text-slate-600 leading-relaxed">
            GogyAI does not guarantee that any AI-generated content is factually accurate, pedagogically sound, or appropriate for your specific students, curriculum, or jurisdiction. Content should be treated as a first draft, not a finished product.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-slate-800 mb-3">Teacher Judgment is Paramount</h2>
          <p className="text-slate-600 leading-relaxed">
            The professional judgment of the teacher supersedes all AI-generated suggestions. No AI tool can replace the knowledge, experience, and contextual understanding that a skilled educator brings to their classroom.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-slate-800 mb-3">IEP and Legal Documents</h2>
          <p className="text-slate-600 leading-relaxed">
            Content generated by tools such as the IEP Goal Writer is for drafting and inspiration purposes only. IEP goals and other legally binding educational documents must be reviewed by qualified special education professionals and comply with applicable law.
          </p>
        </section>
      </div>
    </>
  )
}
